#ifndef __DOE_H__
#define __DOE_H__

#define CXL_DOE_TABLE_ACCESS_REQ_CODE           0x000000ff
#define   CXL_DOE_TABLE_ACCESS_REQ_CODE_READ    0
#define CXL_DOE_TABLE_ACCESS_TABLE_TYPE         0x0000ff00
#define   CXL_DOE_TABLE_ACCESS_TABLE_TYPE_CDATA 0
#define CXL_DOE_TABLE_ACCESS_ENTRY_HANDLE       0xffff0000
#define CXL_DOE_TABLE_ACCESS_LAST_ENTRY         0xffff
#define CXL_DOE_PROTOCOL_TABLE_ACCESS 2

#endif
